### PR TITLE
Use Dapr secrets store

### PR DESCRIPTION
**Pull request by NikiforovAll**
Resolve technical debt pointed out in the code

Solves #100

### CODE REVIEW

**Comment by NikiforovAll** [comment]
✔ It does work for the docker-compose scenario:

image

❌Haven't checked the k8s setup.

**Comment by NikiforovAll** [comment]
Note: it wasn't simple to debug the startup scenario. Can we improve the developer experience for vscode?

**Comment by amolenk** [comment]
@NikiforovAll Awesome, thanks for this! Just got back from holiday, but will review this week and test the K8s scenario as well.

**Comment by amolenk** [comment]
Hi @NikiforovAll 

I did some tests for the K8s side of things and there are some changes that need to be made to get both K8s and Docker Compose deployments working from the same source:

In `/deploy/k8s/helm/templates/secrets.yaml` there are some config lines that need to be uncommented:

```yaml
  # Connection strings are temporarily injected using environment variables
  # while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
  #ConnectionStrings.CatalogDB: U2VydmVyPXNxbGRhdGE7RGF0YWJhc2U9TWljcm9zb2Z0LmVTaG9wT25EYXByLlNlcnZpY2VzLkNhdGFsb2dEYjtVc2VyIElkPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWUK
  #ConnectionStrings.IdentityDB: U2VydmVyPXNxbGRhdGE7RGF0YWJhc2U9TWljcm9zb2Z0LmVTaG9wT25EYXByLlNlcnZpY2UuSWRlbnRpdHlEYjtVc2VyIElkPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWUK
  #ConnectionStrings.OrderingDB: U2VydmVyPXNxbGRhdGE7RGF0YWJhc2U9TWljcm9zb2Z0LmVTaG9wT25EYXByLlNlcnZpY2VzLk9yZGVyaW5nRGI7VXNlciBJZD1zYTtQYXNzd29yZD1QYXNzQHdvcmQ7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVl
```

These config keys use a `.` as the separator character, because it's not allowed to use a `:` character in a K8s config key.

Because we're stuck with the `.` on the K8s side, we need to change the references in the code, e.g.: `builder.Configuration["ConnectionStrings.CatalogDB"]`

Finally, to make sure Docker Compose deployments keep working, we must change the `nestedSeparator` in the secret component config to a `.` as well:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eshopondapr-secretstore
  namespace: eshop
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/eshop-secrets.json
  - name: nestedSeparator
    value: "."
```

**Comment by NikiforovAll** [comment]
Hi @amolenk ,

Thank you for the detailed explanation. I will work on suggested changes in nearest future.  I assume that for now we just want to make it work, so I will use "." as a separator. 

---

Is there something we can do with "." separator to support a standard separator for configuration - ":"?

People are used to the hierarchical configuration in local development like this:

```json
{
  "ConnectionStrings": {
    "CatalogDB": ""
  }
}
```

My guess is that we need to extend the Dapr configuration provider.

**Comment by NikiforovAll** [comment]
**We** may want to use "__" as a separator in k8s scenario. Is it something that you want to do? 

Also, we can use `AddDaprSecretStore` and specify the separator to be used. So we can use ":" in the source code. But it doesn't help in k8s scenario.

```csharp
public static IConfigurationBuilder AddDaprSecretStore(this IConfigurationBuilder configurationBuilder, string store, DaprClient client, IEnumerable<string>? keyDelimiters)
```

**Suggestion:**

Use ":" separator in Dapr secrets store and replace "." with "__" in k8s setup. What do you think?

**Comment by amolenk** [comment]
Yes, good idea. Use `__` in the K8s config keys and `:` in the code and as the configured separator in the component config.

Also, the Identity service doesn't have a Dapr sidecar configured yet in the K8s scripts. It will need one if it's going to get the IdentityDb connection string through the secret building block. The deployment object needs the following annotations in `identity.yaml`:
```yaml
    dapr.io/enabled: "true"
    dapr.io/app-id: "identity-api"
    dapr.io/app-port: "80"
    dapr.io/config: "dapr-config"
    dapr.io/log-as-json: "true"
```

**Comment by NikiforovAll** [comment]
Hi @amolenk ,

I've changed the k8s configuration as we discussed.

**Review by amolenk — APPROVED** [review]

**Pull request merged**
