### PR TITLE
Fix startup errors caused by missing secret store

### PR DESCRIPTION
**Pull request by MarkWme**
As noted in #120 the container apps based deployment was not working because it's missing the `eshopondapr-secretstore ` Dapr component. In this PR, I've fixed that as follows

- Added a bicep file to create a managed identity for Dapr to use to access Key Vault
- Added a bicep file to create a Key Vault along with the secrets for the SQL database connection strings and an access policy to allow the managed identity to retrieve those secrets
- The `identity-api` did not have Dapr enabled, so I've updated the bicep file to do that.
- The `identity-api`, `ordering-api` and `catalog-api` bicep files have been updated to add the managed identity that Dapr will use to access Key Vault.
- Added a bicep file to create the `eshopondapr-secretstore` Dapr component and scope it for use by the `identity-api`, `ordering-api` and `catalog-api`.

I've also enhanced the deployment by adding Application Insights and modifying the Container App Environment bicep file to link to the App Insights instance.  So, you'll now get Application Maps and all the other cool stuff that Dapr and App Insights provide.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnDapr?pullRequest=126) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnDapr?pullRequest=126) before we can accept your contribution.<br/><br/>:x: MarkWme [sign now](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnDapr?pullRequest=126)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-architecture/eShopOnDapr?pullRequest=126) it.</sub>

**Comment by rmcaneny-cs** [comment]
Hi Mark, thanks for look at this! I don't think I can PR it, but I will pull down the code and try it out today and let you know.

**Comment by rmcaneny-cs** [comment]
Mark, this is working for me.  I am able to deploy to ACA and run the store app as well.   The webstatus app shows all services healthy.

**Comment by MarkWme** [comment]
@amolenk - saw that you approved some of the most recent PR's to this repo. Are you still involved and able to approve? Thanks!

**Comment by amolenk** [comment]
Hi @MarkWme,
I'm not directly involved anymore, but I think I can still approve, so let me see what I can do

**Review by amolenk — APPROVED** [review]

**Comment by amolenk** [comment]
@nishanil Approved and merged this PR by @MarkWme because Azure Container Apps deployment was broken due to the addition of a Dapr secretstore to the latest version.

**Pull request merged**
